# Ultralytics YOLO ğŸš€, AGPL-3.0 license

# parent
# â”œâ”€â”€ Ellitesserien 
# â””â”€â”€ datasets
#     â””â”€â”€ 1200 images  â† downloads here (-- MB)


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /home/mehdi/YOLO_Train/Training/datasets  # dataset root dir
train: datasets/train     # train images (relative to 'path') 128 images
val: datasets/valid       # val images (relative to 'path') 128 images
test:  datasets/test        #test images (optional)

# Classes
names:
  0: Ball
  1: Player


